/helpname: ItemExchange
main: com.untamedears.ItemExchange.ItemExchangePlugin
author: gmlaxfanatic
version: 0.1
commands:
  iecreate:
    aliases: iec
    description: Automatically creates an exchange inside the chest the player is looking at
    usage: /iecreate (or /iec) [input or output]
  ieset:
    aliases: ies
    description: Sets the field of the ExchangeRule held in hand
    usage: /ieset (or /ies) <field> [value] [modifier]